# Generated by Django 5.1.3 on 2024-12-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblogging_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_id',
            new_name='id',
        ),
    ]
