# Generated by Django 5.1.3 on 2024-12-09 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblogging_app', '0004_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
