# Generated by Django 5.1.3 on 2024-12-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblogging_app', '0006_post_username_profil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='Bio',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='profil',
            name='username',
            field=models.CharField(default='Romain', max_length=255),
            preserve_default=False,
        ),
    ]
